[2025-02-16T13:22:17.456+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-16T13:22:18.354+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: call_run_operator_dag.task1 scheduled__2025-02-14T21:33:00+00:00 [queued]>
[2025-02-16T13:22:18.463+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: call_run_operator_dag.task1 scheduled__2025-02-14T21:33:00+00:00 [queued]>
[2025-02-16T13:22:18.463+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-16T13:22:18.938+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task1> on 2025-02-14 21:33:00+00:00
[2025-02-16T13:22:18.987+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5321) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-16T13:22:19.014+0000] {standard_task_runner.py:72} INFO - Started process 5359 to run task
[2025-02-16T13:22:19.074+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'call_run_operator_dag', 'task1', 'scheduled__2025-02-14T21:33:00+00:00', '--job-id', '872', '--raw', '--subdir', 'DAGS_FOLDER/11_run_operator_dag.py', '--cfg-path', '/tmp/tmpho3wozer']
[2025-02-16T13:22:19.086+0000] {standard_task_runner.py:105} INFO - Job 872: Subtask task1
[2025-02-16T13:22:20.232+0000] {task_command.py:467} INFO - Running <TaskInstance: call_run_operator_dag.task1 scheduled__2025-02-14T21:33:00+00:00 [running]> on host ab74d4d90d32
[2025-02-16T13:22:21.582+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='call_run_operator_dag' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T21:33:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-14T21:33:00+00:00'
[2025-02-16T13:22:21.586+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-16T13:22:22.158+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-16T13:22:22.190+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'sleep 5']
[2025-02-16T13:22:22.279+0000] {subprocess.py:99} INFO - Output:
[2025-02-16T13:22:24.365+0000] {job.py:229} INFO - Heartbeat recovered after 13.27 seconds
[2025-02-16T13:22:27.352+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-16T13:22:28.091+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-16T13:22:28.191+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=call_run_operator_dag, task_id=task1, run_id=scheduled__2025-02-14T21:33:00+00:00, execution_date=20250214T213300, start_date=20250216T132218, end_date=20250216T132228
[2025-02-16T13:22:28.932+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-16T13:22:29.096+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-16T13:22:29.101+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-02-16T13:22:29.104+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
