[2025-02-18T21:08:10.428+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T21:08:10.472+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: variable_dag.variable_task manual__2025-02-18T21:08:08.324165+00:00 [queued]>
[2025-02-18T21:08:10.492+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: variable_dag.variable_task manual__2025-02-18T21:08:08.324165+00:00 [queued]>
[2025-02-18T21:08:10.493+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-18T21:08:10.537+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): variable_task> on 2025-02-18 21:08:08.324165+00:00
[2025-02-18T21:08:10.548+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=292) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-18T21:08:10.551+0000] {standard_task_runner.py:72} INFO - Started process 293 to run task
[2025-02-18T21:08:10.551+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'variable_dag', 'variable_task', 'manual__2025-02-18T21:08:08.324165+00:00', '--job-id', '1012', '--raw', '--subdir', 'DAGS_FOLDER/16_variable_dag.py', '--cfg-path', '/tmp/tmpy_1o2qti']
[2025-02-18T21:08:10.554+0000] {standard_task_runner.py:105} INFO - Job 1012: Subtask variable_task
[2025-02-18T21:08:10.685+0000] {task_command.py:467} INFO - Running <TaskInstance: variable_dag.variable_task manual__2025-02-18T21:08:08.324165+00:00 [running]> on host ab74d4d90d32
[2025-02-18T21:08:10.958+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='variable_dag' AIRFLOW_CTX_TASK_ID='variable_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-18T21:08:08.324165+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-18T21:08:08.324165+00:00'
[2025-02-18T21:08:10.960+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-18T21:08:11.027+0000] {logging_mixin.py:190} INFO - Variable value is: ~/workspace/app/***
[2025-02-18T21:08:11.029+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-18T21:08:11.060+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-18T21:08:11.061+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=variable_dag, task_id=variable_task, run_id=manual__2025-02-18T21:08:08.324165+00:00, execution_date=20250218T210808, start_date=20250218T210810, end_date=20250218T210811
[2025-02-18T21:08:11.140+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T21:08:11.176+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-18T21:08:11.181+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
