[2025-02-21T20:21:42.043+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-21T20:21:42.061+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hooks.create_table_task manual__2025-02-21T20:21:40.588079+00:00 [queued]>
[2025-02-21T20:21:42.072+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hooks.create_table_task manual__2025-02-21T20:21:40.588079+00:00 [queued]>
[2025-02-21T20:21:42.073+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-21T20:21:42.088+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_table_task> on 2025-02-21 20:21:40.588079+00:00
[2025-02-21T20:21:42.092+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=355) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-21T20:21:42.093+0000] {standard_task_runner.py:72} INFO - Started process 356 to run task
[2025-02-21T20:21:42.094+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'hooks', 'create_table_task', 'manual__2025-02-21T20:21:40.588079+00:00', '--job-id', '1055', '--raw', '--subdir', 'DAGS_FOLDER/23_hooks_postgres_dag.py', '--cfg-path', '/tmp/tmpw4revjm8']
[2025-02-21T20:21:42.096+0000] {standard_task_runner.py:105} INFO - Job 1055: Subtask create_table_task
[2025-02-21T20:21:42.153+0000] {task_command.py:467} INFO - Running <TaskInstance: hooks.create_table_task manual__2025-02-21T20:21:40.588079+00:00 [running]> on host 70b8189021ad
[2025-02-21T20:21:42.288+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hooks' AIRFLOW_CTX_TASK_ID='create_table_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T20:21:40.588079+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-21T20:21:40.588079+00:00'
[2025-02-21T20:21:42.291+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-21T20:21:42.335+0000] {base.py:84} INFO - Retrieving connection 'postgres-postgres'
[2025-02-21T20:21:42.341+0000] {sql.py:511} INFO - Running statement: CREATE TABLE IF NOT EXISTS teste_hook(id int), parameters: None
[2025-02-21T20:21:42.342+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-21T20:21:42.368+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-21T20:21:42.368+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=hooks, task_id=create_table_task, run_id=manual__2025-02-21T20:21:40.588079+00:00, execution_date=20250221T202140, start_date=20250221T202142, end_date=20250221T202142
[2025-02-21T20:21:42.433+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-21T20:21:42.482+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-21T20:21:42.485+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
