[2025-02-16T13:22:01.370+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-16T13:22:02.588+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_operator_dag.task1 scheduled__2025-02-14T21:33:00+00:00 [queued]>
[2025-02-16T13:22:03.392+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_operator_dag.task1 scheduled__2025-02-14T21:33:00+00:00 [queued]>
[2025-02-16T13:22:03.392+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-16T13:22:04.405+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task1> on 2025-02-14 21:33:00+00:00
[2025-02-16T13:22:05.050+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'run_operator_dag', 'task1', 'scheduled__2025-02-14T21:33:00+00:00', '--job-id', '866', '--raw', '--subdir', 'DAGS_FOLDER/10_run_operator_dag.py', '--cfg-path', '/tmp/tmp3xk6s3un']
[2025-02-16T13:22:05.079+0000] {standard_task_runner.py:105} INFO - Job 866: Subtask task1
[2025-02-16T13:22:04.800+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5310) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-16T13:22:05.080+0000] {standard_task_runner.py:72} INFO - Started process 5338 to run task
[2025-02-16T13:22:06.417+0000] {task_command.py:467} INFO - Running <TaskInstance: run_operator_dag.task1 scheduled__2025-02-14T21:33:00+00:00 [running]> on host ab74d4d90d32
[2025-02-16T13:22:10.934+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_operator_dag' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T21:33:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-14T21:33:00+00:00'
[2025-02-16T13:22:10.935+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-16T13:22:11.308+0000] {job.py:229} INFO - Heartbeat recovered after 13.18 seconds
[2025-02-16T13:22:11.936+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-16T13:22:11.987+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'sleep 5']
[2025-02-16T13:22:15.702+0000] {subprocess.py:99} INFO - Output:
[2025-02-16T13:22:20.734+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-16T13:22:21.003+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-16T13:22:21.004+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=run_operator_dag, task_id=task1, run_id=scheduled__2025-02-14T21:33:00+00:00, execution_date=20250214T213300, start_date=20250216T132202, end_date=20250216T132221
[2025-02-16T13:22:21.656+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-16T13:22:22.144+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-16T13:22:22.153+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
