[2025-02-18T02:00:07.347+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T02:00:07.377+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: default_args_dag.task2 scheduled__2025-02-18T01:00:00+00:00 [queued]>
[2025-02-18T02:00:07.402+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: default_args_dag.task2 scheduled__2025-02-18T01:00:00+00:00 [queued]>
[2025-02-18T02:00:07.403+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-18T02:00:07.429+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task2> on 2025-02-18 01:00:00+00:00
[2025-02-18T02:00:07.435+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=11273) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-18T02:00:07.436+0000] {standard_task_runner.py:72} INFO - Started process 11274 to run task
[2025-02-18T02:00:07.439+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'default_args_dag', 'task2', 'scheduled__2025-02-18T01:00:00+00:00', '--job-id', '994', '--raw', '--subdir', 'DAGS_FOLDER/12_default_args_dag.py', '--cfg-path', '/tmp/tmphh5i2e04']
[2025-02-18T02:00:07.441+0000] {standard_task_runner.py:105} INFO - Job 994: Subtask task2
[2025-02-18T02:00:07.510+0000] {task_command.py:467} INFO - Running <TaskInstance: default_args_dag.task2 scheduled__2025-02-18T01:00:00+00:00 [running]> on host ab74d4d90d32
[2025-02-18T02:00:07.606+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@test.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='default_args_dag' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2025-02-18T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-18T01:00:00+00:00'
[2025-02-18T02:00:07.608+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-18T02:00:07.631+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-18T02:00:07.632+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'sleep 5']
[2025-02-18T02:00:07.641+0000] {subprocess.py:99} INFO - Output:
[2025-02-18T02:00:16.237+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-18T02:00:16.295+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-18T02:00:16.296+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=default_args_dag, task_id=task2, run_id=scheduled__2025-02-18T01:00:00+00:00, execution_date=20250218T010000, start_date=20250218T020007, end_date=20250218T020016
[2025-02-18T02:00:16.361+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T02:00:16.381+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-18T02:00:16.383+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
