[2025-02-21T20:18:28.004+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-21T20:18:28.030+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hooks.select_data_task manual__2025-02-21T20:17:13.249656+00:00 [queued]>
[2025-02-21T20:18:28.042+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hooks.select_data_task manual__2025-02-21T20:17:13.249656+00:00 [queued]>
[2025-02-21T20:18:28.043+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-02-21T20:18:28.069+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): select_data_task> on 2025-02-21 20:17:13.249656+00:00
[2025-02-21T20:18:28.074+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=298) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-21T20:18:28.077+0000] {standard_task_runner.py:72} INFO - Started process 299 to run task
[2025-02-21T20:18:28.077+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'hooks', 'select_data_task', 'manual__2025-02-21T20:17:13.249656+00:00', '--job-id', '1050', '--raw', '--subdir', 'DAGS_FOLDER/23_hooks_postgres_dag.py', '--cfg-path', '/tmp/tmp2glmb45z']
[2025-02-21T20:18:28.079+0000] {standard_task_runner.py:105} INFO - Job 1050: Subtask select_data_task
[2025-02-21T20:18:28.211+0000] {task_command.py:467} INFO - Running <TaskInstance: hooks.select_data_task manual__2025-02-21T20:17:13.249656+00:00 [running]> on host 70b8189021ad
[2025-02-21T20:18:28.357+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hooks' AIRFLOW_CTX_TASK_ID='select_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T20:17:13.249656+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-21T20:17:13.249656+00:00'
[2025-02-21T20:18:28.358+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-21T20:18:28.392+0000] {base.py:84} INFO - Retrieving connection 'postgres-postgres'
[2025-02-21T20:18:28.395+0000] {sql.py:511} INFO - Running statement: select * from teste_hook, parameters: None
[2025-02-21T20:18:28.397+0000] {sql.py:520} INFO - Rows affected: 2
[2025-02-21T20:18:28.412+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-21T20:18:28.427+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-21T20:18:28.428+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=hooks, task_id=select_data_task, run_id=manual__2025-02-21T20:17:13.249656+00:00, execution_date=20250221T201713, start_date=20250221T201828, end_date=20250221T201828
[2025-02-21T20:18:28.494+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-21T20:18:28.530+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-21T20:18:28.532+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
