[2025-02-16T13:22:39.946+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-16T13:22:40.437+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: call_run_operator_dag.run_dag_task scheduled__2025-02-14T21:33:00+00:00 [queued]>
[2025-02-16T13:22:40.574+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: call_run_operator_dag.run_dag_task scheduled__2025-02-14T21:33:00+00:00 [queued]>
[2025-02-16T13:22:40.574+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-16T13:22:40.915+0000] {taskinstance.py:2890} INFO - Executing <Task(TriggerDagRunOperator): run_dag_task> on 2025-02-14 21:33:00+00:00
[2025-02-16T13:22:41.128+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5374) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-16T13:22:41.213+0000] {standard_task_runner.py:72} INFO - Started process 5392 to run task
[2025-02-16T13:22:41.217+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'call_run_operator_dag', 'run_dag_task', 'scheduled__2025-02-14T21:33:00+00:00', '--job-id', '880', '--raw', '--subdir', 'DAGS_FOLDER/11_run_operator_dag.py', '--cfg-path', '/tmp/tmp9xj28_e2']
[2025-02-16T13:22:41.230+0000] {standard_task_runner.py:105} INFO - Job 880: Subtask run_dag_task
[2025-02-16T13:22:41.705+0000] {task_command.py:467} INFO - Running <TaskInstance: call_run_operator_dag.run_dag_task scheduled__2025-02-14T21:33:00+00:00 [running]> on host ab74d4d90d32
[2025-02-16T13:22:42.780+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='call_run_operator_dag' AIRFLOW_CTX_TASK_ID='run_dag_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T21:33:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-14T21:33:00+00:00'
[2025-02-16T13:22:42.781+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-16T13:22:44.159+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-16T13:22:44.160+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=call_run_operator_dag, task_id=run_dag_task, run_id=scheduled__2025-02-14T21:33:00+00:00, execution_date=20250214T213300, start_date=20250216T132240, end_date=20250216T132244
[2025-02-16T13:22:44.415+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-16T13:22:44.490+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-16T13:22:44.520+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
