[2025-02-18T21:45:38.411+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T21:45:38.441+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: branch_dag.even_number_task manual__2025-02-18T21:45:33.427674+00:00 [queued]>
[2025-02-18T21:45:38.458+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: branch_dag.even_number_task manual__2025-02-18T21:45:33.427674+00:00 [queued]>
[2025-02-18T21:45:38.459+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-18T21:45:38.482+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): even_number_task> on 2025-02-18 21:45:33.427674+00:00
[2025-02-18T21:45:38.486+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=790) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-18T21:45:38.488+0000] {standard_task_runner.py:72} INFO - Started process 791 to run task
[2025-02-18T21:45:38.488+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'branch_dag', 'even_number_task', 'manual__2025-02-18T21:45:33.427674+00:00', '--job-id', '1032', '--raw', '--subdir', 'DAGS_FOLDER/18_branch_dag.py', '--cfg-path', '/tmp/tmpp931asj_']
[2025-02-18T21:45:38.490+0000] {standard_task_runner.py:105} INFO - Job 1032: Subtask even_number_task
[2025-02-18T21:45:38.549+0000] {task_command.py:467} INFO - Running <TaskInstance: branch_dag.even_number_task manual__2025-02-18T21:45:33.427674+00:00 [running]> on host ab74d4d90d32
[2025-02-18T21:45:38.678+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='branch_dag' AIRFLOW_CTX_TASK_ID='even_number_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-18T21:45:33.427674+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-18T21:45:33.427674+00:00'
[2025-02-18T21:45:38.679+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-18T21:45:38.700+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-18T21:45:38.701+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'Even Number'"]
[2025-02-18T21:45:38.713+0000] {subprocess.py:99} INFO - Output:
[2025-02-18T21:45:38.715+0000] {subprocess.py:106} INFO - Even Number
[2025-02-18T21:45:38.715+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-18T21:45:38.749+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-18T21:45:38.750+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=branch_dag, task_id=even_number_task, run_id=manual__2025-02-18T21:45:33.427674+00:00, execution_date=20250218T214533, start_date=20250218T214538, end_date=20250218T214538
[2025-02-18T21:45:38.825+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T21:45:38.855+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-18T21:45:38.857+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
