[2025-02-18T21:44:47.380+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T21:44:47.426+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: branch_dag.even_number_task manual__2025-02-18T21:41:14.924806+00:00 [queued]>
[2025-02-18T21:44:47.444+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: branch_dag.even_number_task manual__2025-02-18T21:41:14.924806+00:00 [queued]>
[2025-02-18T21:44:47.444+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-18T21:44:47.470+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): even_number_task> on 2025-02-18 21:41:14.924806+00:00
[2025-02-18T21:44:47.477+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=774) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-18T21:44:47.478+0000] {standard_task_runner.py:72} INFO - Started process 775 to run task
[2025-02-18T21:44:47.479+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'branch_dag', 'even_number_task', 'manual__2025-02-18T21:41:14.924806+00:00', '--job-id', '1029', '--raw', '--subdir', 'DAGS_FOLDER/18_branch_dag.py', '--cfg-path', '/tmp/tmpfuegd7he']
[2025-02-18T21:44:47.480+0000] {standard_task_runner.py:105} INFO - Job 1029: Subtask even_number_task
[2025-02-18T21:44:47.567+0000] {task_command.py:467} INFO - Running <TaskInstance: branch_dag.even_number_task manual__2025-02-18T21:41:14.924806+00:00 [running]> on host ab74d4d90d32
[2025-02-18T21:44:47.693+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='branch_dag' AIRFLOW_CTX_TASK_ID='even_number_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-18T21:41:14.924806+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-18T21:41:14.924806+00:00'
[2025-02-18T21:44:47.694+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-18T21:44:47.713+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-18T21:44:47.715+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'Even Number'"]
[2025-02-18T21:44:47.725+0000] {subprocess.py:99} INFO - Output:
[2025-02-18T21:44:47.728+0000] {subprocess.py:106} INFO - Even Number
[2025-02-18T21:44:47.728+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-18T21:44:47.756+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-18T21:44:47.757+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=branch_dag, task_id=even_number_task, run_id=manual__2025-02-18T21:41:14.924806+00:00, execution_date=20250218T214114, start_date=20250218T214447, end_date=20250218T214447
[2025-02-18T21:44:47.816+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T21:44:47.837+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-18T21:44:47.839+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
