[2025-02-16T13:22:34.391+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-16T13:22:35.055+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_operator_dag.task2 scheduled__2025-02-14T21:33:00+00:00 [queued]>
[2025-02-16T13:22:35.580+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_operator_dag.task2 scheduled__2025-02-14T21:33:00+00:00 [queued]>
[2025-02-16T13:22:35.581+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-16T13:22:36.639+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task2> on 2025-02-14 21:33:00+00:00
[2025-02-16T13:22:36.703+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5366) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-16T13:22:36.705+0000] {standard_task_runner.py:72} INFO - Started process 5382 to run task
[2025-02-16T13:22:36.735+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'run_operator_dag', 'task2', 'scheduled__2025-02-14T21:33:00+00:00', '--job-id', '875', '--raw', '--subdir', 'DAGS_FOLDER/10_run_operator_dag.py', '--cfg-path', '/tmp/tmprfvqa67l']
[2025-02-16T13:22:36.902+0000] {standard_task_runner.py:105} INFO - Job 875: Subtask task2
[2025-02-16T13:22:37.819+0000] {task_command.py:467} INFO - Running <TaskInstance: run_operator_dag.task2 scheduled__2025-02-14T21:33:00+00:00 [running]> on host ab74d4d90d32
[2025-02-16T13:22:40.022+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_operator_dag' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T21:33:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-14T21:33:00+00:00'
[2025-02-16T13:22:40.023+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-16T13:22:40.607+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-16T13:22:40.664+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'sleep 5']
[2025-02-16T13:22:40.744+0000] {subprocess.py:99} INFO - Output:
[2025-02-16T13:22:45.837+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-16T13:22:46.097+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-16T13:22:46.098+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=run_operator_dag, task_id=task2, run_id=scheduled__2025-02-14T21:33:00+00:00, execution_date=20250214T213300, start_date=20250216T132235, end_date=20250216T132246
[2025-02-16T13:22:46.464+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-16T13:22:46.679+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-16T13:22:46.744+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-16T13:22:46.861+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
